import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Montserrat } from "next/font/google";
import { Toaster } from "sonner";
import "../styles/globals.css";
import { Analytics } from "@vercel/analytics/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const fonts = `${geistSans.variable} ${geistMono.variable} ${inter.variable} ${montserrat.variable}`;
  return (
    <html lang="en">
      <body className={`${fonts} antialiased bg-neutral-100`}>
        {children}
        <Toaster richColors closeButton />
        <Analytics />
      </body>
    </html>
  );
}
